# -*- coding: utf-8 -*-
"""Gradient Boosting Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u8olsDpM0RyVeMxopRhAs1oKYf8Yuwmu
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import KNNImputer
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder, OrdinalEncoder
from xgboost import XGBRegressor
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

df = pd.read_csv("/content/Housing.csv")

df

df.info()

df.isna().sum()

x = df.drop("price", axis=1)
y = df["price"]

num_cols = ["area", "bedrooms", "bathrooms", "stories", "parking"]
one_hot_cols = ["mainroad", "guestroom", "basement", "hotwaterheating", "airconditioning", "prefarea"]
ordinal_cols = ["furnishingstatus"]

furnish_order = [[f for f in x["furnishingstatus"].unique()][::-1]]

furnish_order

num_pipeline = Pipeline([
    ("scalar", StandardScaler())
])

one_hot_pipeline = Pipeline([
    ("one_hot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

ordinal_pipeline = Pipeline([
    ("ordinal", OrdinalEncoder(categories=furnish_order, handle_unknown="use_encoded_value", unknown_value=-1))
])

preprocessor = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("one_hot", one_hot_pipeline, one_hot_cols),
    ("ordinal", ordinal_pipeline, ordinal_cols)
 ], remainder="passthrough"
)

full_pipeline = Pipeline([
    ("preprocessing", preprocessor),
    ("model", XGBRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    objective='reg:squarederror'
))
])

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

full_pipeline.fit(xtrain, ytrain)

predict = mean_absolute_error(ytest, full_pipeline.predict(xtest))

average = y.mean()

average

(average - predict)/average

r2_score(ytest, full_pipeline.predict(xtest))

